[manifest]
version = "1.0.0"
dump_lua = true
priority = 214748364

[[patches]] #G.Game.current_round
[patches.pattern]
target = 'game.lua'
pattern = '''
reroll_cost_increase = 0,
'''
position = 'after'
match_indent = true
payload = '''
jest_magick_joker_card = {suit = 'Spades'},
'''

[[patches]]  
[patches.pattern]
target = 'game.lua'
pattern = '''
reset_castle_card()
'''
position = 'after'
match_indent = true
payload = '''
reset_jest_magick_joker_card()
'''